[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

solc = "0.8.26"
optimize = true
via-ir = true

[fuzz]
max_test_rejects = 100000

[fmt]
line_length = 120

[profile.gas-report]
gas_reports = ["Chaos"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
