[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [{ access = "read", path = "./"}]
# gas_limit increase necessary to handle subcalls in LibConsistent()
# test loops.
gas_limit = "18446744073709551615"
[fuzz]
max_test_rejects = 100000

[fmt]
line_length = 120

[profile.gas-report]
gas_reports = ["Chaos"]
[profile.default.optimizer_details]
yul=false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
